const FilingMaster = require('../models/FilingMaster');

const DEFAULT_FILING_MASTERS = [
  {
    code: 'GSTR-1',
    name: 'GSTR-1 (Outward Supplies)',
    category: 'GST',
    frequency: 'Monthly',
    dueDay: 11,
    dueOffsetMonths: 1,
    governmentPortal: 'GSTN',
    governmentFormCode: 'GSTR1',
    department: 'Accounts',
    description: 'Monthly statement of outward supplies of goods or services.',
    companyDueDateNote: 'Due by 11th of the month following the tax period.',
  },
  {
    code: 'GSTR-3B',
    name: 'GSTR-3B (Summary Return)',
    category: 'GST',
    frequency: 'Monthly',
    dueDay: 20,
    dueOffsetMonths: 1,
    governmentPortal: 'GSTN',
    governmentFormCode: 'GSTR3B',
    department: 'Accounts',
    description: 'Monthly summary return of outward and inward supplies with tax payment.',
    companyDueDateNote: 'Due by 20th of the month following the tax period.',
  },
  {
    code: 'GSTR-9',
    name: 'GSTR-9 (Annual Return)',
    category: 'GST',
    frequency: 'Annual',
    dueDay: 31,
    dueMonth: 12,
    governmentPortal: 'GSTN',
    governmentFormCode: 'GSTR9',
    department: 'Accounts',
    description: 'Annual consolidated GST return for the financial year.',
    companyDueDateNote: 'Typically due by 31 December after FY end (verify current CBIC notification).',
  },
  {
    code: 'TDS-24Q',
    name: 'TDS Return 24Q (Salary)',
    category: 'TDS',
    frequency: 'Quarterly',
    dueDay: 31,
    dueOffsetMonths: 1,
    governmentPortal: 'Income Tax',
    governmentFormCode: '24Q',
    department: 'Accounts',
    description: 'Quarterly TDS statement for tax deducted on salary payments.',
    companyDueDateNote: 'Due by last day of month following quarter end.',
  },
  {
    code: 'TDS-26Q',
    name: 'TDS Return 26Q (Non-Salary)',
    category: 'TDS',
    frequency: 'Quarterly',
    dueDay: 31,
    dueOffsetMonths: 1,
    governmentPortal: 'Income Tax',
    governmentFormCode: '26Q',
    department: 'Accounts',
    description: 'Quarterly TDS statement for non-salary payments.',
    companyDueDateNote: 'Due by last day of month following quarter end.',
  },
  {
    code: 'ITR-6',
    name: 'Income Tax Return (Company)',
    category: 'ITR',
    frequency: 'Annual',
    dueDay: 31,
    dueMonth: 10,
    governmentPortal: 'Income Tax',
    governmentFormCode: 'ITR6',
    department: 'Accounts',
    description: 'Annual income tax return filing for companies.',
    companyDueDateNote: 'Typically due by 31 October after FY end (verify current Finance Act due dates).',
  },
  {
    code: 'EPF-ECR',
    name: 'EPF Electronic Challan cum Return',
    category: 'EPF',
    frequency: 'Monthly',
    dueDay: 15,
    dueOffsetMonths: 1,
    governmentPortal: 'EPFO',
    governmentFormCode: 'ECR',
    department: 'HR',
    description: 'Monthly EPF contribution and return filing.',
    companyDueDateNote: 'Due by 15th of the following month.',
  },
  {
    code: 'ESIC-RETURN',
    name: 'ESIC Half-Yearly Return',
    category: 'ESIC',
    frequency: 'Half-Yearly',
    dueDay: 11,
    dueMonth: 5,
    governmentPortal: 'ESIC',
    governmentFormCode: 'HALF_YEARLY',
    department: 'HR',
    description: 'Half-yearly ESIC contribution return.',
    companyDueDateNote: 'Due by 11th May and 11th November for respective contribution periods.',
  },
  {
    code: 'PT-RETURN',
    name: 'Professional Tax Return',
    category: 'Labour',
    frequency: 'Monthly',
    dueDay: 20,
    dueOffsetMonths: 1,
    governmentPortal: 'State Portal',
    governmentFormCode: 'PT',
    department: 'HR',
    description: 'State professional tax return as applicable.',
    companyDueDateNote: 'Due date varies by state; adjust per company registration.',
  },
];

async function seedFilingMastersIfEmpty() {
  const count = await FilingMaster.countDocuments();
  if (count > 0) return { seeded: false, count };

  await FilingMaster.insertMany(DEFAULT_FILING_MASTERS);
  return { seeded: true, count: DEFAULT_FILING_MASTERS.length };
}

module.exports = {
  DEFAULT_FILING_MASTERS,
  seedFilingMastersIfEmpty,
};
