const { EMPLOYEE_DEPARTMENTS } = require('./departments');

const DEFAULT_DEPARTMENTS = EMPLOYEE_DEPARTMENTS.map((name, index) => ({
  code: name.slice(0, 4).toUpperCase().replace(/\s/g, ''),
  name,
  description: `${name} department`,
  isActive: true,
  sortOrder: index + 1,
}));

const DEFAULT_DESIGNATIONS = [
  { name: 'Warehouse Manager', department: 'Warehouse', grade: 'L3', sortOrder: 1 },
  { name: 'Warehouse Executive', department: 'Warehouse', grade: 'L2', sortOrder: 2 },
  { name: 'Store Keeper', department: 'Warehouse', grade: 'L1', sortOrder: 3 },
  { name: 'Stock Manager', department: 'Stocks', grade: 'L3', sortOrder: 4 },
  { name: 'Inventory Executive', department: 'Stocks', grade: 'L2', sortOrder: 5 },
  { name: 'Accounts Manager', department: 'Accounts', grade: 'L3', sortOrder: 6 },
  { name: 'Accountant', department: 'Accounts', grade: 'L2', sortOrder: 7 },
  { name: 'Accounts Executive', department: 'Accounts', grade: 'L1', sortOrder: 8 },
  { name: 'HR Manager', department: 'HR', grade: 'L3', sortOrder: 9 },
  { name: 'HR Executive', department: 'HR', grade: 'L2', sortOrder: 10 },
  { name: 'Admin Executive', department: 'HR', grade: 'L1', sortOrder: 11 },
].map((row) => ({ ...row, isActive: true, description: '' }));

const DEFAULT_PAYROLL_COMPONENTS = [
  {
    code: 'BASIC',
    name: 'Basic Salary',
    category: 'earning',
    calculationType: 'fixed',
    defaultValue: 0,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 1,
    description: 'Employee basic pay (from employee master)',
  },
  {
    code: 'HRA',
    name: 'House Rent Allowance',
    category: 'earning',
    calculationType: 'weight',
    defaultValue: 35,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 2,
  },
  {
    code: 'DA',
    name: 'Dearness Allowance',
    category: 'earning',
    calculationType: 'weight',
    defaultValue: 12,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 3,
  },
  {
    code: 'SPECIAL',
    name: 'Special Allowance',
    category: 'earning',
    calculationType: 'weight',
    defaultValue: 22,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 4,
  },
  {
    code: 'MEDICAL',
    name: 'Medical Allowance',
    category: 'earning',
    calculationType: 'weight',
    defaultValue: 8,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 5,
  },
  {
    code: 'TRAVEL',
    name: 'Travel Allowance',
    category: 'earning',
    calculationType: 'weight',
    defaultValue: 8,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 6,
  },
  {
    code: 'BONUS',
    name: 'Performance Bonus',
    category: 'earning',
    calculationType: 'weight',
    defaultValue: 7,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 7,
  },
  {
    code: 'OT',
    name: 'Overtime',
    category: 'earning',
    calculationType: 'weight',
    defaultValue: 4,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 8,
  },
  {
    code: 'OTHER_EARN',
    name: 'Other Allowances',
    category: 'earning',
    calculationType: 'weight',
    defaultValue: 4,
    isStatutory: false,
    isTaxable: true,
    sortOrder: 9,
  },
  {
    code: 'PF',
    name: 'Provident Fund (Employee)',
    category: 'deduction',
    calculationType: 'percent_of_basic',
    defaultValue: 12,
    isStatutory: true,
    isTaxable: false,
    sortOrder: 10,
    description: 'Employee PF contribution',
  },
  {
    code: 'ESI',
    name: 'Employee State Insurance',
    category: 'deduction',
    calculationType: 'percent_of_gross',
    defaultValue: 0.75,
    isStatutory: true,
    isTaxable: false,
    sortOrder: 11,
    description: 'Applicable when basic ≤ 21,000',
  },
  {
    code: 'PT',
    name: 'Professional Tax',
    category: 'deduction',
    calculationType: 'fixed',
    defaultValue: 200,
    isStatutory: true,
    isTaxable: false,
    sortOrder: 12,
  },
  {
    code: 'IT',
    name: 'Income Tax / TDS',
    category: 'deduction',
    calculationType: 'fixed',
    defaultValue: 0,
    isStatutory: true,
    isTaxable: false,
    sortOrder: 13,
  },
  {
    code: 'ADVANCE',
    name: 'Advance Recovery',
    category: 'deduction',
    calculationType: 'fixed',
    defaultValue: 0,
    isStatutory: false,
    isTaxable: false,
    sortOrder: 14,
  },
  {
    code: 'LOAN',
    name: 'Loan Recovery',
    category: 'deduction',
    calculationType: 'fixed',
    defaultValue: 0,
    isStatutory: false,
    isTaxable: false,
    sortOrder: 15,
  },
  {
    code: 'LOP',
    name: 'Leave Without Pay Deduction',
    category: 'deduction',
    calculationType: 'fixed',
    defaultValue: 0,
    isStatutory: false,
    isTaxable: false,
    sortOrder: 16,
  },
  {
    code: 'OTHER_DED',
    name: 'Other Deductions',
    category: 'deduction',
    calculationType: 'fixed',
    defaultValue: 0,
    isStatutory: false,
    isTaxable: false,
    sortOrder: 17,
  },
  {
    code: 'EPF_ER',
    name: 'Employer Provident Fund',
    category: 'employer',
    calculationType: 'percent_of_basic',
    defaultValue: 12,
    isStatutory: true,
    isTaxable: false,
    sortOrder: 18,
  },
  {
    code: 'ESI_ER',
    name: 'Employer ESI',
    category: 'employer',
    calculationType: 'percent_of_gross',
    defaultValue: 3.25,
    isStatutory: true,
    isTaxable: false,
    sortOrder: 19,
  },
  {
    code: 'GRATUITY',
    name: 'Gratuity Provision',
    category: 'employer',
    calculationType: 'percent_of_basic',
    defaultValue: 4.81,
    isStatutory: true,
    isTaxable: false,
    sortOrder: 20,
  },
];

module.exports = {
  DEFAULT_DEPARTMENTS,
  DEFAULT_DESIGNATIONS,
  DEFAULT_PAYROLL_COMPONENTS,
};
