const Permission = require('../models/Permission');

const PERMISSION_DEFINITIONS = [
  { code: 'admin.all', name: 'Full Admin', module: 'admin', description: 'Full system access' },
  { code: 'products.view', name: 'View Products', module: 'products', description: 'View products' },
  { code: 'products.create', name: 'Create Products', module: 'products', description: 'Create products' },
  { code: 'products.update', name: 'Update Products', module: 'products', description: 'Update products' },
  { code: 'products.delete', name: 'Delete Products', module: 'products', description: 'Delete products' },
  { code: 'categories.view', name: 'View Categories', module: 'categories', description: 'View categories' },
  { code: 'categories.create', name: 'Create Categories', module: 'categories', description: 'Create categories' },
  { code: 'categories.update', name: 'Update Categories', module: 'categories', description: 'Update categories' },
  { code: 'categories.delete', name: 'Delete Categories', module: 'categories', description: 'Delete categories' },
  { code: 'subcategories.view', name: 'View Subcategories', module: 'subcategories', description: 'View subcategories' },
  { code: 'subcategories.create', name: 'Create Subcategories', module: 'subcategories', description: 'Create subcategories' },
  { code: 'subcategories.update', name: 'Update Subcategories', module: 'subcategories', description: 'Update subcategories' },
  { code: 'subcategories.delete', name: 'Delete Subcategories', module: 'subcategories', description: 'Delete subcategories' },
  { code: 'stock.view', name: 'View Stock', module: 'stock', description: 'View stock' },
  { code: 'stock.create', name: 'Create Stock', module: 'stock', description: 'Create stock entries' },
  { code: 'stock.update', name: 'Update Stock', module: 'stock', description: 'Update stock' },
  { code: 'stock.delete', name: 'Delete Stock', module: 'stock', description: 'Delete stock' },
  { code: 'sales.view', name: 'View Sales', module: 'sales', description: 'View sales' },
  { code: 'sales.create', name: 'Create Sales', module: 'sales', description: 'Create sales' },
  { code: 'sales.update', name: 'Update Sales', module: 'sales', description: 'Update sales' },
  { code: 'sales.delete', name: 'Delete Sales', module: 'sales', description: 'Delete sales' },
  { code: 'purchases.view', name: 'View Purchases', module: 'purchases', description: 'View purchases' },
  { code: 'purchases.create', name: 'Create Purchases', module: 'purchases', description: 'Create purchases' },
  { code: 'purchases.update', name: 'Update Purchases', module: 'purchases', description: 'Update purchases' },
  { code: 'purchases.delete', name: 'Delete Purchases', module: 'purchases', description: 'Delete purchases' },
  { code: 'reports.view', name: 'View Reports', module: 'reports', description: 'View reports' },
  { code: 'reports.export', name: 'Export Reports', module: 'reports', description: 'Export reports' },
  { code: 'users.view', name: 'View Users', module: 'users', description: 'View users' },
  { code: 'users.create', name: 'Create Users', module: 'users', description: 'Create users' },
  { code: 'users.update', name: 'Update Users', module: 'users', description: 'Update users' },
  { code: 'users.delete', name: 'Delete Users', module: 'users', description: 'Delete users' },
  { code: 'roles.view', name: 'View Roles', module: 'roles', description: 'View roles' },
  { code: 'roles.create', name: 'Create Roles', module: 'roles', description: 'Create roles' },
  { code: 'roles.update', name: 'Update Roles', module: 'roles', description: 'Update roles' },
  { code: 'roles.delete', name: 'Delete Roles', module: 'roles', description: 'Delete roles' },
  { code: 'groups.view', name: 'View Groups', module: 'groups', description: 'View groups' },
  { code: 'groups.create', name: 'Create Groups', module: 'groups', description: 'Create groups' },
  { code: 'groups.update', name: 'Update Groups', module: 'groups', description: 'Update groups' },
  { code: 'groups.delete', name: 'Delete Groups', module: 'groups', description: 'Delete groups' },
  { code: 'permissions.view', name: 'View Permissions', module: 'permissions', description: 'View permissions' },
  { code: 'permissions.create', name: 'Create Permissions', module: 'permissions', description: 'Create permissions' },
  { code: 'permissions.update', name: 'Update Permissions', module: 'permissions', description: 'Update permissions' },
  { code: 'permissions.delete', name: 'Delete Permissions', module: 'permissions', description: 'Delete permissions' },
  // Additional modules from the ERP
  { code: 'suppliers.view', name: 'View Suppliers', module: 'suppliers', description: 'View suppliers' },
  { code: 'suppliers.create', name: 'Create Suppliers', module: 'suppliers', description: 'Create suppliers' },
  { code: 'suppliers.update', name: 'Update Suppliers', module: 'suppliers', description: 'Update suppliers' },
  { code: 'suppliers.delete', name: 'Delete Suppliers', module: 'suppliers', description: 'Delete suppliers' },
  { code: 'locations.view', name: 'View Locations', module: 'locations', description: 'View locations' },
  { code: 'locations.create', name: 'Create Locations', module: 'locations', description: 'Create locations' },
  { code: 'locations.update', name: 'Update Locations', module: 'locations', description: 'Update locations' },
  { code: 'locations.delete', name: 'Delete Locations', module: 'locations', description: 'Delete locations' },
  { code: 'prices.view', name: 'View Prices', module: 'prices', description: 'View prices' },
  { code: 'prices.create', name: 'Create Prices', module: 'prices', description: 'Create prices' },
  { code: 'prices.update', name: 'Update Prices', module: 'prices', description: 'Update prices' },
  { code: 'prices.delete', name: 'Delete Prices', module: 'prices', description: 'Delete prices' },
  { code: 'priceMasters.view', name: 'View Price Masters', module: 'priceMasters', description: 'View price masters' },
  { code: 'priceMasters.create', name: 'Create Price Masters', module: 'priceMasters', description: 'Create price masters' },
  { code: 'priceMasters.update', name: 'Update Price Masters', module: 'priceMasters', description: 'Update price masters' },
  { code: 'priceMasters.delete', name: 'Delete Price Masters', module: 'priceMasters', description: 'Delete price masters' },
  { code: 'units.view', name: 'View Units', module: 'units', description: 'View units' },
  { code: 'units.create', name: 'Create Units', module: 'units', description: 'Create units' },
  { code: 'units.update', name: 'Update Units', module: 'units', description: 'Update units' },
  { code: 'units.delete', name: 'Delete Units', module: 'units', description: 'Delete units' },
  { code: 'shipments.view', name: 'View Shipments', module: 'shipments', description: 'View shipments' },
  { code: 'shipments.create', name: 'Create Shipments', module: 'shipments', description: 'Create shipments' },
  { code: 'shipments.update', name: 'Update Shipments', module: 'shipments', description: 'Update shipments' },
  { code: 'shipments.delete', name: 'Delete Shipments', module: 'shipments', description: 'Delete shipments' },
  { code: 'gemini.view', name: 'View Image Generator', module: 'gemini', description: 'Access image generator' },
  { code: 'gemini.generate', name: 'Generate Images', module: 'gemini', description: 'Generate images' },
  { code: 'purchaseOrders.view', name: 'View Purchase Orders', module: 'purchaseOrders', description: 'View purchase orders' },
  { code: 'purchaseOrders.create', name: 'Create Purchase Orders', module: 'purchaseOrders', description: 'Create purchase orders' },
  { code: 'purchaseOrders.update', name: 'Update Purchase Orders', module: 'purchaseOrders', description: 'Update purchase orders' },
  { code: 'purchaseOrders.delete', name: 'Delete Purchase Orders', module: 'purchaseOrders', description: 'Delete purchase orders' },
  { code: 'salesChannels.view', name: 'View Sales Channels', module: 'salesChannels', description: 'View sales channels' },
  { code: 'salesChannels.create', name: 'Create Sales Channels', module: 'salesChannels', description: 'Create sales channels' },
  { code: 'salesChannels.update', name: 'Update Sales Channels', module: 'salesChannels', description: 'Update sales channels' },
  { code: 'salesChannels.delete', name: 'Delete Sales Channels', module: 'salesChannels', description: 'Delete sales channels' },
  { code: 'salesLocations.view', name: 'View Sales Locations', module: 'salesLocations', description: 'View sales locations' },
  { code: 'salesLocations.create', name: 'Create Sales Locations', module: 'salesLocations', description: 'Create sales locations' },
  { code: 'salesLocations.update', name: 'Update Sales Locations', module: 'salesLocations', description: 'Update sales locations' },
  { code: 'salesLocations.delete', name: 'Delete Sales Locations', module: 'salesLocations', description: 'Delete sales locations' },
  { code: 'shipmentVendors.view', name: 'View Shipment Vendors', module: 'shipmentVendors', description: 'View shipment vendors' },
  { code: 'shipmentVendors.create', name: 'Create Shipment Vendors', module: 'shipmentVendors', description: 'Create shipment vendors' },
  { code: 'shipmentVendors.update', name: 'Update Shipment Vendors', module: 'shipmentVendors', description: 'Update shipment vendors' },
  { code: 'shipmentVendors.delete', name: 'Delete Shipment Vendors', module: 'shipmentVendors', description: 'Delete shipment vendors' },
  { code: 'companyProfile.view', name: 'View Company Master', module: 'companyProfile', description: 'View company master profile' },
  { code: 'companyProfile.update', name: 'Update Company Master', module: 'companyProfile', description: 'Update company master profile' },
  { code: 'master.full', name: 'Full Master Access', module: 'master', description: 'Full access to all Master pages' },
  { code: 'shippingCharges.view', name: 'View Shipping Charges', module: 'shippingCharges', description: 'View shipping charges' },
  { code: 'shippingCharges.create', name: 'Create Shipping Charges', module: 'shippingCharges', description: 'Create shipping charges' },
  { code: 'shippingCharges.update', name: 'Update Shipping Charges', module: 'shippingCharges', description: 'Update shipping charges' },
  { code: 'shippingCharges.delete', name: 'Delete Shipping Charges', module: 'shippingCharges', description: 'Delete shipping charges' },
  { code: 'logs.view', name: 'View Logs', module: 'logs', description: 'View application and employee activity logs' },
  { code: 'logs.create', name: 'Create Logs', module: 'logs', description: 'Create log entries (e.g. frontend logging)' },
  { code: 'logs.delete', name: 'Delete Logs', module: 'logs', description: 'Delete logs' },
  { code: 'hr.access', name: 'Access HR Module', module: 'hr', description: 'View and use HR module features' },

  // Compliance module
  { code: 'compliance.access', name: 'Access Compliance Module', module: 'compliance', description: 'Access the Compliance module navigation' },
  { code: 'compliance.full', name: 'Full Compliance Access', module: 'compliance', description: 'Full create/update/delete across Compliance' },
  { code: 'compliance.dashboard.view', name: 'View Compliance Dashboard', module: 'compliance', description: 'View compliance dashboard' },
  { code: 'compliance.company.view', name: 'View Company Information', module: 'compliance', description: 'View compliance company information' },
  { code: 'compliance.company.update', name: 'Update Company Information', module: 'compliance', description: 'Update compliance company information' },
  { code: 'compliance.filingMaster.view', name: 'View Filing Master', module: 'compliance', description: 'View compliance filing master forms' },
  { code: 'compliance.filingMaster.create', name: 'Create Filing Master', module: 'compliance', description: 'Create filing master forms' },
  { code: 'compliance.filingMaster.update', name: 'Update Filing Master', module: 'compliance', description: 'Update filing master forms' },
  { code: 'compliance.filingMaster.delete', name: 'Delete Filing Master', module: 'compliance', description: 'Delete filing master forms' },
  { code: 'compliance.filings.view', name: 'View Filings', module: 'compliance', description: 'View compliance filing records' },
  { code: 'compliance.filings.create', name: 'Create Filings', module: 'compliance', description: 'Create compliance filing records' },
  { code: 'compliance.filings.update', name: 'Update Filings', module: 'compliance', description: 'Update and submit compliance filings' },
  { code: 'compliance.filings.delete', name: 'Delete Filings', module: 'compliance', description: 'Delete compliance filing records' },
  { code: 'compliance.gst.view', name: 'View GST Compliance', module: 'compliance', description: 'View GST filings' },
  { code: 'compliance.gst.create', name: 'Create GST Compliance', module: 'compliance', description: 'Create GST filings' },
  { code: 'compliance.gst.update', name: 'Update GST Compliance', module: 'compliance', description: 'Update GST filings' },
  { code: 'compliance.gst.delete', name: 'Delete GST Compliance', module: 'compliance', description: 'Delete GST filings' },
  { code: 'compliance.tds.view', name: 'View Income Tax & TDS', module: 'compliance', description: 'View TDS filings' },
  { code: 'compliance.tds.create', name: 'Create Income Tax & TDS', module: 'compliance', description: 'Create TDS filings' },
  { code: 'compliance.tds.update', name: 'Update Income Tax & TDS', module: 'compliance', description: 'Update TDS filings' },
  { code: 'compliance.tds.delete', name: 'Delete Income Tax & TDS', module: 'compliance', description: 'Delete TDS filings' },
  { code: 'compliance.payroll.view', name: 'View Payroll Compliance', module: 'compliance', description: 'View payroll registers' },
  { code: 'compliance.payroll.create', name: 'Create Payroll Compliance', module: 'compliance', description: 'Create payroll registers' },
  { code: 'compliance.payroll.update', name: 'Update Payroll Compliance', module: 'compliance', description: 'Update payroll registers' },
  { code: 'compliance.payroll.delete', name: 'Delete Payroll Compliance', module: 'compliance', description: 'Delete payroll registers' },
  { code: 'compliance.epf.view', name: 'View EPF Compliance', module: 'compliance', description: 'View EPF filings' },
  { code: 'compliance.epf.create', name: 'Create EPF Compliance', module: 'compliance', description: 'Create EPF filings' },
  { code: 'compliance.epf.update', name: 'Update EPF Compliance', module: 'compliance', description: 'Update EPF filings' },
  { code: 'compliance.epf.delete', name: 'Delete EPF Compliance', module: 'compliance', description: 'Delete EPF filings' },
  { code: 'compliance.esic.view', name: 'View ESIC Compliance', module: 'compliance', description: 'View ESIC filings' },
  { code: 'compliance.esic.create', name: 'Create ESIC Compliance', module: 'compliance', description: 'Create ESIC filings' },
  { code: 'compliance.esic.update', name: 'Update ESIC Compliance', module: 'compliance', description: 'Update ESIC filings' },
  { code: 'compliance.esic.delete', name: 'Delete ESIC Compliance', module: 'compliance', description: 'Delete ESIC filings' },
  { code: 'compliance.labour.view', name: 'View Labour Compliance', module: 'compliance', description: 'View labour registers' },
  { code: 'compliance.labour.create', name: 'Create Labour Compliance', module: 'compliance', description: 'Create labour registers' },
  { code: 'compliance.labour.update', name: 'Update Labour Compliance', module: 'compliance', description: 'Update labour registers' },
  { code: 'compliance.labour.delete', name: 'Delete Labour Compliance', module: 'compliance', description: 'Delete labour registers' },
  { code: 'compliance.employees.view', name: 'View Employee Compliance', module: 'compliance', description: 'View employee compliance records' },
  { code: 'compliance.employees.create', name: 'Create Employee Compliance', module: 'compliance', description: 'Create employee compliance records' },
  { code: 'compliance.employees.update', name: 'Update Employee Compliance', module: 'compliance', description: 'Update employee compliance records' },
  { code: 'compliance.employees.delete', name: 'Delete Employee Compliance', module: 'compliance', description: 'Delete employee compliance records' },
  { code: 'compliance.licenses.view', name: 'View Licenses', module: 'compliance', description: 'View company licenses' },
  { code: 'compliance.licenses.create', name: 'Create Licenses', module: 'compliance', description: 'Create company licenses' },
  { code: 'compliance.licenses.update', name: 'Update Licenses', module: 'compliance', description: 'Update company licenses' },
  { code: 'compliance.licenses.delete', name: 'Delete Licenses', module: 'compliance', description: 'Delete company licenses' },
  { code: 'compliance.audits.view', name: 'View Audit Reports', module: 'compliance', description: 'View audit reports' },
  { code: 'compliance.audits.create', name: 'Create Audit Reports', module: 'compliance', description: 'Create audit reports' },
  { code: 'compliance.audits.update', name: 'Update Audit Reports', module: 'compliance', description: 'Update audit reports' },
  { code: 'compliance.audits.delete', name: 'Delete Audit Reports', module: 'compliance', description: 'Delete audit reports' },
  { code: 'compliance.calendar.view', name: 'View Compliance Calendar', module: 'compliance', description: 'View compliance calendar' },
  { code: 'compliance.documents.view', name: 'View Document Repository', module: 'compliance', description: 'View compliance documents' },
  { code: 'compliance.documents.create', name: 'Upload Compliance Documents', module: 'compliance', description: 'Upload compliance documents' },
  { code: 'compliance.documents.update', name: 'Update Compliance Documents', module: 'compliance', description: 'Update compliance documents' },
  { code: 'compliance.documents.delete', name: 'Delete Compliance Documents', module: 'compliance', description: 'Delete compliance documents' },
  { code: 'compliance.reports.view', name: 'View Compliance Reports', module: 'compliance', description: 'View and export compliance reports' },

  // Finance module
  { code: 'finance.access', name: 'Access Finance Module', module: 'finance', description: 'Access Finance navigation' },
  { code: 'finance.full', name: 'Full Finance Access', module: 'finance', description: 'Full access across Finance module' },
  { code: 'finance.dashboard.view', name: 'View Finance Dashboard', module: 'finance', description: 'View finance dashboard' },
  { code: 'finance.income.view', name: 'View Income Report', module: 'finance', description: 'View income reports' },
  { code: 'finance.income.create', name: 'Create Income Entries', module: 'finance', description: 'Create manual income records' },
  { code: 'finance.income.update', name: 'Update Income Entries', module: 'finance', description: 'Update manual income records' },
  { code: 'finance.income.delete', name: 'Delete Income Entries', module: 'finance', description: 'Delete manual income records' },
  { code: 'finance.expense.view', name: 'View Expense Report', module: 'finance', description: 'View expense reports' },
  { code: 'finance.expense.create', name: 'Create Expenses', module: 'finance', description: 'Create expense records' },
  { code: 'finance.expense.update', name: 'Update Expenses', module: 'finance', description: 'Update expense records' },
  { code: 'finance.expense.delete', name: 'Delete Expenses', module: 'finance', description: 'Delete expense records' },
  { code: 'finance.pnl.view', name: 'View Profit & Loss', module: 'finance', description: 'View profit and loss statements' },
  { code: 'finance.reports.view', name: 'View Finance Reports', module: 'finance', description: 'View and export finance reports' },

  // Document Management module
  { code: 'documents.access', name: 'Access Document Management', module: 'documents', description: 'Access Document Management navigation' },
  { code: 'documents.full', name: 'Full Document Management Access', module: 'documents', description: 'Full access across Document Management' },
  { code: 'documents.view', name: 'View Documents', module: 'documents', description: 'View documents' },
  { code: 'documents.create', name: 'Create Documents', module: 'documents', description: 'Upload and save documents' },
  { code: 'documents.upload', name: 'Upload Documents', module: 'documents', description: 'Upload employee documents' },
  { code: 'documents.update', name: 'Update Documents', module: 'documents', description: 'Update document metadata' },
  { code: 'documents.delete', name: 'Delete Documents', module: 'documents', description: 'Soft or permanent delete documents' },
  { code: 'documents.download', name: 'Download Documents', module: 'documents', description: 'Download documents' },
  { code: 'documents.manage', name: 'Manage Document Storage', module: 'documents', description: 'Manage storage settings and permanent deletes' },
  { code: 'documents.dashboard.view', name: 'View Documents Dashboard', module: 'documents', description: 'View document management dashboard' },
  { code: 'documents.ai.view', name: 'View AI Generated Images', module: 'documents', description: 'View AI-generated images' },
  { code: 'documents.manual.view', name: 'View Employee Documents', module: 'documents', description: 'View employee uploaded documents' },
  { code: 'documents.analytics.view', name: 'View Storage Analytics', module: 'documents', description: 'View storage analytics' },
  { code: 'documents.trash.view', name: 'View Document Trash', module: 'documents', description: 'View soft-deleted documents' },
  { code: 'documents.settings.view', name: 'View Document Settings', module: 'documents', description: 'View document settings' },
  { code: 'documents.settings.update', name: 'Update Document Settings', module: 'documents', description: 'Update document settings' },
  { code: 'documents.department.view', name: 'View Department Documents', module: 'documents', description: 'Manager view of department documents' },
];

async function seedPermissions() {
  try {
    let created = 0;
    for (const def of PERMISSION_DEFINITIONS) {
      const existing = await Permission.findOne({ code: def.code });
      if (!existing) {
        await Permission.create(def);
        created++;
      }
    }
    return { created, total: PERMISSION_DEFINITIONS.length };
  } catch (error) {
    console.error('seedPermissions error:', error.message);
    throw error;
  }
}

module.exports = { seedPermissions, PERMISSION_DEFINITIONS };
